version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: stockfy-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: stockfy
      POSTGRES_PASSWORD: stockfy
      POSTGRES_DB: stockfy
    ports:
      - "5432:5432"
    volumes:
      - stockfy_pgdata:/var/lib/postgresql/data

volumes:
  stockfy_pgdata:
